---
extends:
  - eslint:recommended
#  - plugin:import/errors
#  - plugin:import/warnings
#  - plugin:flowtype/recommended

parser: babel-eslint

globals:
  Class: false

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    modules: true

plugins:
  - import
#  - flowtype

env:
  node: true
  es6: true

rules:
  arrow-parens: 0
  quote-props: 0
  no-process-env: 0
  no-console: 0

  semi:
    - 2

  no-unused-vars:
    - 2
    - argsIgnorePattern: '^_'

  no-warning-comments:
    - 1

  import/no-unresolved:
    - 2
    - commonjs: true
