// flow-typed signature: 505d8eb9f325cb2f374ba587a249e110
// flow-typed version: <<STUB>>/docker-file-parser_v^1.0.2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'docker-file-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'docker-file-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'docker-file-parser/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'docker-file-parser/index' {
  declare module.exports: $Exports<'docker-file-parser'>;
}
declare module 'docker-file-parser/index.js' {
  declare module.exports: $Exports<'docker-file-parser'>;
}
declare module 'docker-file-parser/parser.js' {
  declare module.exports: $Exports<'docker-file-parser/parser'>;
}
