// flow-typed signature: 001380299d532ccef18a5b0fc91141a7
// flow-typed version: <<STUB>>/fast-json-patch_v^1.1.10/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-json-patch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-json-patch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-json-patch/dist/json-patch-duplex.min' {
  declare module.exports: any;
}

declare module 'fast-json-patch/dist/json-patch.min' {
  declare module.exports: any;
}

declare module 'fast-json-patch/src/json-patch-duplex' {
  declare module.exports: any;
}

declare module 'fast-json-patch/src/json-patch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-json-patch/dist/json-patch-duplex.min.js' {
  declare module.exports: $Exports<'fast-json-patch/dist/json-patch-duplex.min'>;
}
declare module 'fast-json-patch/dist/json-patch.min.js' {
  declare module.exports: $Exports<'fast-json-patch/dist/json-patch.min'>;
}
declare module 'fast-json-patch/src/json-patch-duplex.js' {
  declare module.exports: $Exports<'fast-json-patch/src/json-patch-duplex'>;
}
declare module 'fast-json-patch/src/json-patch.js' {
  declare module.exports: $Exports<'fast-json-patch/src/json-patch'>;
}
