// flow-typed signature: 5b366aca894b97876607cf9c58fc57c4
// flow-typed version: <<STUB>>/jsonpath_v^0.2.11/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonpath'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonpath' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonpath/bin/generate_parser' {
  declare module.exports: any;
}

declare module 'jsonpath/generated/aesprim-browser' {
  declare module.exports: any;
}

declare module 'jsonpath/generated/parser' {
  declare module.exports: any;
}

declare module 'jsonpath/Gruntfile' {
  declare module.exports: any;
}

declare module 'jsonpath/include/action' {
  declare module.exports: any;
}

declare module 'jsonpath/include/module' {
  declare module.exports: any;
}

declare module 'jsonpath/jsonpath' {
  declare module.exports: any;
}

declare module 'jsonpath/jsonpath.min' {
  declare module.exports: any;
}

declare module 'jsonpath/lib/aesprim' {
  declare module.exports: any;
}

declare module 'jsonpath/lib/dict' {
  declare module.exports: any;
}

declare module 'jsonpath/lib/grammar' {
  declare module.exports: any;
}

declare module 'jsonpath/lib/handlers' {
  declare module.exports: any;
}

declare module 'jsonpath/lib/index' {
  declare module.exports: any;
}

declare module 'jsonpath/lib/parser' {
  declare module.exports: any;
}

declare module 'jsonpath/lib/slice' {
  declare module.exports: any;
}

declare module 'jsonpath/test/lessons' {
  declare module.exports: any;
}

declare module 'jsonpath/test/parse' {
  declare module.exports: any;
}

declare module 'jsonpath/test/query' {
  declare module.exports: any;
}

declare module 'jsonpath/test/slice' {
  declare module.exports: any;
}

declare module 'jsonpath/test/stringify' {
  declare module.exports: any;
}

declare module 'jsonpath/test/sugar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonpath/bin/generate_parser.js' {
  declare module.exports: $Exports<'jsonpath/bin/generate_parser'>;
}
declare module 'jsonpath/generated/aesprim-browser.js' {
  declare module.exports: $Exports<'jsonpath/generated/aesprim-browser'>;
}
declare module 'jsonpath/generated/parser.js' {
  declare module.exports: $Exports<'jsonpath/generated/parser'>;
}
declare module 'jsonpath/Gruntfile.js' {
  declare module.exports: $Exports<'jsonpath/Gruntfile'>;
}
declare module 'jsonpath/include/action.js' {
  declare module.exports: $Exports<'jsonpath/include/action'>;
}
declare module 'jsonpath/include/module.js' {
  declare module.exports: $Exports<'jsonpath/include/module'>;
}
declare module 'jsonpath/index' {
  declare module.exports: $Exports<'jsonpath'>;
}
declare module 'jsonpath/index.js' {
  declare module.exports: $Exports<'jsonpath'>;
}
declare module 'jsonpath/jsonpath.js' {
  declare module.exports: $Exports<'jsonpath/jsonpath'>;
}
declare module 'jsonpath/jsonpath.min.js' {
  declare module.exports: $Exports<'jsonpath/jsonpath.min'>;
}
declare module 'jsonpath/lib/aesprim.js' {
  declare module.exports: $Exports<'jsonpath/lib/aesprim'>;
}
declare module 'jsonpath/lib/dict.js' {
  declare module.exports: $Exports<'jsonpath/lib/dict'>;
}
declare module 'jsonpath/lib/grammar.js' {
  declare module.exports: $Exports<'jsonpath/lib/grammar'>;
}
declare module 'jsonpath/lib/handlers.js' {
  declare module.exports: $Exports<'jsonpath/lib/handlers'>;
}
declare module 'jsonpath/lib/index.js' {
  declare module.exports: $Exports<'jsonpath/lib/index'>;
}
declare module 'jsonpath/lib/parser.js' {
  declare module.exports: $Exports<'jsonpath/lib/parser'>;
}
declare module 'jsonpath/lib/slice.js' {
  declare module.exports: $Exports<'jsonpath/lib/slice'>;
}
declare module 'jsonpath/test/lessons.js' {
  declare module.exports: $Exports<'jsonpath/test/lessons'>;
}
declare module 'jsonpath/test/parse.js' {
  declare module.exports: $Exports<'jsonpath/test/parse'>;
}
declare module 'jsonpath/test/query.js' {
  declare module.exports: $Exports<'jsonpath/test/query'>;
}
declare module 'jsonpath/test/slice.js' {
  declare module.exports: $Exports<'jsonpath/test/slice'>;
}
declare module 'jsonpath/test/stringify.js' {
  declare module.exports: $Exports<'jsonpath/test/stringify'>;
}
declare module 'jsonpath/test/sugar.js' {
  declare module.exports: $Exports<'jsonpath/test/sugar'>;
}
