// flow-typed signature: 64dc034a66924d64db7854a1c13e201e
// flow-typed version: <<STUB>>/nunjucks_v^3.0.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nunjucks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nunjucks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nunjucks/bin/bundle' {
  declare module.exports: any;
}

declare module 'nunjucks/browser/nunjucks-slim' {
  declare module.exports: any;
}

declare module 'nunjucks/browser/nunjucks-slim.min' {
  declare module.exports: any;
}

declare module 'nunjucks/browser/nunjucks' {
  declare module.exports: any;
}

declare module 'nunjucks/browser/nunjucks.min' {
  declare module.exports: any;
}

declare module 'nunjucks/src/compiler' {
  declare module.exports: any;
}

declare module 'nunjucks/src/environment' {
  declare module.exports: any;
}

declare module 'nunjucks/src/filters' {
  declare module.exports: any;
}

declare module 'nunjucks/src/globals' {
  declare module.exports: any;
}

declare module 'nunjucks/src/jinja-compat' {
  declare module.exports: any;
}

declare module 'nunjucks/src/lexer' {
  declare module.exports: any;
}

declare module 'nunjucks/src/lib' {
  declare module.exports: any;
}

declare module 'nunjucks/src/loader' {
  declare module.exports: any;
}

declare module 'nunjucks/src/loaders' {
  declare module.exports: any;
}

declare module 'nunjucks/src/node-loaders' {
  declare module.exports: any;
}

declare module 'nunjucks/src/nodes' {
  declare module.exports: any;
}

declare module 'nunjucks/src/object' {
  declare module.exports: any;
}

declare module 'nunjucks/src/parser' {
  declare module.exports: any;
}

declare module 'nunjucks/src/precompile-global' {
  declare module.exports: any;
}

declare module 'nunjucks/src/precompile' {
  declare module.exports: any;
}

declare module 'nunjucks/src/precompiled-loader' {
  declare module.exports: any;
}

declare module 'nunjucks/src/runtime' {
  declare module.exports: any;
}

declare module 'nunjucks/src/transformer' {
  declare module.exports: any;
}

declare module 'nunjucks/src/web-loaders' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nunjucks/bin/bundle.js' {
  declare module.exports: $Exports<'nunjucks/bin/bundle'>;
}
declare module 'nunjucks/browser/nunjucks-slim.js' {
  declare module.exports: $Exports<'nunjucks/browser/nunjucks-slim'>;
}
declare module 'nunjucks/browser/nunjucks-slim.min.js' {
  declare module.exports: $Exports<'nunjucks/browser/nunjucks-slim.min'>;
}
declare module 'nunjucks/browser/nunjucks.js' {
  declare module.exports: $Exports<'nunjucks/browser/nunjucks'>;
}
declare module 'nunjucks/browser/nunjucks.min.js' {
  declare module.exports: $Exports<'nunjucks/browser/nunjucks.min'>;
}
declare module 'nunjucks/index' {
  declare module.exports: $Exports<'nunjucks'>;
}
declare module 'nunjucks/index.js' {
  declare module.exports: $Exports<'nunjucks'>;
}
declare module 'nunjucks/src/compiler.js' {
  declare module.exports: $Exports<'nunjucks/src/compiler'>;
}
declare module 'nunjucks/src/environment.js' {
  declare module.exports: $Exports<'nunjucks/src/environment'>;
}
declare module 'nunjucks/src/filters.js' {
  declare module.exports: $Exports<'nunjucks/src/filters'>;
}
declare module 'nunjucks/src/globals.js' {
  declare module.exports: $Exports<'nunjucks/src/globals'>;
}
declare module 'nunjucks/src/jinja-compat.js' {
  declare module.exports: $Exports<'nunjucks/src/jinja-compat'>;
}
declare module 'nunjucks/src/lexer.js' {
  declare module.exports: $Exports<'nunjucks/src/lexer'>;
}
declare module 'nunjucks/src/lib.js' {
  declare module.exports: $Exports<'nunjucks/src/lib'>;
}
declare module 'nunjucks/src/loader.js' {
  declare module.exports: $Exports<'nunjucks/src/loader'>;
}
declare module 'nunjucks/src/loaders.js' {
  declare module.exports: $Exports<'nunjucks/src/loaders'>;
}
declare module 'nunjucks/src/node-loaders.js' {
  declare module.exports: $Exports<'nunjucks/src/node-loaders'>;
}
declare module 'nunjucks/src/nodes.js' {
  declare module.exports: $Exports<'nunjucks/src/nodes'>;
}
declare module 'nunjucks/src/object.js' {
  declare module.exports: $Exports<'nunjucks/src/object'>;
}
declare module 'nunjucks/src/parser.js' {
  declare module.exports: $Exports<'nunjucks/src/parser'>;
}
declare module 'nunjucks/src/precompile-global.js' {
  declare module.exports: $Exports<'nunjucks/src/precompile-global'>;
}
declare module 'nunjucks/src/precompile.js' {
  declare module.exports: $Exports<'nunjucks/src/precompile'>;
}
declare module 'nunjucks/src/precompiled-loader.js' {
  declare module.exports: $Exports<'nunjucks/src/precompiled-loader'>;
}
declare module 'nunjucks/src/runtime.js' {
  declare module.exports: $Exports<'nunjucks/src/runtime'>;
}
declare module 'nunjucks/src/transformer.js' {
  declare module.exports: $Exports<'nunjucks/src/transformer'>;
}
declare module 'nunjucks/src/web-loaders.js' {
  declare module.exports: $Exports<'nunjucks/src/web-loaders'>;
}
