// flow-typed signature: 864add2b6ea60400cde7ae948039f920
// flow-typed version: <<STUB>>/yawn-yaml_v^1.3.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yawn-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yawn-yaml' {
  declare module.exports: any;
}

// manually added 
declare module 'yawn-yaml/cjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yawn-yaml/cjs/error' {
  declare module.exports: any;
}

declare module 'yawn-yaml/cjs/index' {
  declare module.exports: any;
}

declare module 'yawn-yaml/dist/yawn' {
  declare module.exports: any;
}

declare module 'yawn-yaml/src/error' {
  declare module.exports: any;
}

declare module 'yawn-yaml/src/index' {
  declare module.exports: any;
}

declare module 'yawn-yaml/test/array' {
  declare module.exports: any;
}

declare module 'yawn-yaml/test/deep' {
  declare module.exports: any;
}

declare module 'yawn-yaml/test/end-to-end' {
  declare module.exports: any;
}

declare module 'yawn-yaml/test/lint' {
  declare module.exports: any;
}

declare module 'yawn-yaml/test/number' {
  declare module.exports: any;
}

declare module 'yawn-yaml/test/object' {
  declare module.exports: any;
}

declare module 'yawn-yaml/test/string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yawn-yaml/cjs/error.js' {
  declare module.exports: $Exports<'yawn-yaml/cjs/error'>;
}
declare module 'yawn-yaml/cjs/index.js' {
  declare module.exports: $Exports<'yawn-yaml/cjs/index'>;
}
declare module 'yawn-yaml/dist/yawn.js' {
  declare module.exports: $Exports<'yawn-yaml/dist/yawn'>;
}
declare module 'yawn-yaml/src/error.js' {
  declare module.exports: $Exports<'yawn-yaml/src/error'>;
}
declare module 'yawn-yaml/src/index.js' {
  declare module.exports: $Exports<'yawn-yaml/src/index'>;
}
declare module 'yawn-yaml/test/array.js' {
  declare module.exports: $Exports<'yawn-yaml/test/array'>;
}
declare module 'yawn-yaml/test/deep.js' {
  declare module.exports: $Exports<'yawn-yaml/test/deep'>;
}
declare module 'yawn-yaml/test/end-to-end.js' {
  declare module.exports: $Exports<'yawn-yaml/test/end-to-end'>;
}
declare module 'yawn-yaml/test/lint.js' {
  declare module.exports: $Exports<'yawn-yaml/test/lint'>;
}
declare module 'yawn-yaml/test/number.js' {
  declare module.exports: $Exports<'yawn-yaml/test/number'>;
}
declare module 'yawn-yaml/test/object.js' {
  declare module.exports: $Exports<'yawn-yaml/test/object'>;
}
declare module 'yawn-yaml/test/string.js' {
  declare module.exports: $Exports<'yawn-yaml/test/string'>;
}
