// flow-typed signature: e800df9dbbdc0b8235e47c87d6442fe2
// flow-typed version: <<STUB>>/@google-cloud/functions-emulator_v^1.0.0-alpha.20/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@google-cloud/functions-emulator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@google-cloud/functions-emulator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@google-cloud/functions-emulator/mocks' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/call' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/clear' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/config/defaults' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/config/index' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/config/list' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/config/reset' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/config/set' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/debug' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/delete' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/deploy' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/describe' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/event-types/index' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/event-types/list' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/inspect' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/kill' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/list' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/logs/clear' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/logs/index' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/logs/read' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/prune' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/reset' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/restart' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/start' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/status' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/commands/stop' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/controller' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/examples' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/index' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/cli/main' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/client/client' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/client/grpc-client' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/client/index' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/client/rest-client' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/config' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/emulator/emulator' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/emulator/index' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/emulator/logs' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/emulator/main' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/model/cloudfunction' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/model/functions' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/model/index' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/model/operation' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/model/protos' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/options' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/server' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/service/grpc-service' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/service/index' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/service/rest-service' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/service/service' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/supervisor/index' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/supervisor/supervisor' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/supervisor/worker' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/utils/detectProjectId' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/utils/errors' {
  declare module.exports: any;
}

declare module '@google-cloud/functions-emulator/src/utils/schema' {
  declare module.exports: any;
}

// Filename aliases
declare module '@google-cloud/functions-emulator/mocks.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/mocks'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/call.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/call'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/clear.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/clear'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/config/defaults.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/config/defaults'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/config/index.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/config/index'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/config/list.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/config/list'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/config/reset.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/config/reset'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/config/set.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/config/set'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/debug.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/debug'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/delete.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/delete'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/deploy.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/deploy'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/describe.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/describe'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/event-types/index.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/event-types/index'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/event-types/list.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/event-types/list'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/inspect.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/inspect'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/kill.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/kill'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/list.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/list'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/logs/clear.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/logs/clear'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/logs/index.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/logs/index'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/logs/read.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/logs/read'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/prune.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/prune'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/reset.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/reset'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/restart.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/restart'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/start.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/start'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/status.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/status'>;
}
declare module '@google-cloud/functions-emulator/src/cli/commands/stop.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/commands/stop'>;
}
declare module '@google-cloud/functions-emulator/src/cli/controller.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/controller'>;
}
declare module '@google-cloud/functions-emulator/src/cli/examples.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/examples'>;
}
declare module '@google-cloud/functions-emulator/src/cli/index.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/index'>;
}
declare module '@google-cloud/functions-emulator/src/cli/main.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/cli/main'>;
}
declare module '@google-cloud/functions-emulator/src/client/client.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/client/client'>;
}
declare module '@google-cloud/functions-emulator/src/client/grpc-client.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/client/grpc-client'>;
}
declare module '@google-cloud/functions-emulator/src/client/index.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/client/index'>;
}
declare module '@google-cloud/functions-emulator/src/client/rest-client.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/client/rest-client'>;
}
declare module '@google-cloud/functions-emulator/src/config.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/config'>;
}
declare module '@google-cloud/functions-emulator/src/emulator/emulator.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/emulator/emulator'>;
}
declare module '@google-cloud/functions-emulator/src/emulator/index.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/emulator/index'>;
}
declare module '@google-cloud/functions-emulator/src/emulator/logs.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/emulator/logs'>;
}
declare module '@google-cloud/functions-emulator/src/emulator/main.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/emulator/main'>;
}
declare module '@google-cloud/functions-emulator/src/model/cloudfunction.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/model/cloudfunction'>;
}
declare module '@google-cloud/functions-emulator/src/model/functions.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/model/functions'>;
}
declare module '@google-cloud/functions-emulator/src/model/index.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/model/index'>;
}
declare module '@google-cloud/functions-emulator/src/model/operation.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/model/operation'>;
}
declare module '@google-cloud/functions-emulator/src/model/protos.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/model/protos'>;
}
declare module '@google-cloud/functions-emulator/src/options.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/options'>;
}
declare module '@google-cloud/functions-emulator/src/server.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/server'>;
}
declare module '@google-cloud/functions-emulator/src/service/grpc-service.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/service/grpc-service'>;
}
declare module '@google-cloud/functions-emulator/src/service/index.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/service/index'>;
}
declare module '@google-cloud/functions-emulator/src/service/rest-service.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/service/rest-service'>;
}
declare module '@google-cloud/functions-emulator/src/service/service.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/service/service'>;
}
declare module '@google-cloud/functions-emulator/src/supervisor/index.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/supervisor/index'>;
}
declare module '@google-cloud/functions-emulator/src/supervisor/supervisor.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/supervisor/supervisor'>;
}
declare module '@google-cloud/functions-emulator/src/supervisor/worker.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/supervisor/worker'>;
}
declare module '@google-cloud/functions-emulator/src/utils/detectProjectId.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/utils/detectProjectId'>;
}
declare module '@google-cloud/functions-emulator/src/utils/errors.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/utils/errors'>;
}
declare module '@google-cloud/functions-emulator/src/utils/schema.js' {
  declare module.exports: $Exports<'@google-cloud/functions-emulator/src/utils/schema'>;
}
